# -*- coding: utf-8 -*-
"""StockMarket Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLDjVkXjkEhaLnZGnNuh3N6ct0ikz2Fg
"""

import pandas as pd
from datetime import datetime
import numpy as np
import datetime as dt

df=pd.read_excel('/content/Sample StockMarket Data (1).xlsx')

df.head(5)

df.rename(columns={'Unnamed: 0':'Ticker','Unnamed: 1':'Date','Unnamed: 2':'Time','Unnamed: 3':'Open', 'Unnamed: 4':'High','Unnamed: 5':'Low','Unnamed: 6':'Close','Unnamed: 7':'Volume','Unnamed: 8':'Open Interest'},inplace=True)

df.info()

df.head()

df = df.iloc[1:]

df.head()

#Convert the Date column to a pandas datetime format
df['Date'] = pd.to_datetime(df['Date'])
groups = df.groupby(df['Date'][:10])

#
print(df['Date'].max())
print(df['Date'].min())

#
df = df.dropna(subset=['Date'])

len(df)
import decimal
import datetime

df['Date'] = pd.to_datetime(df['Date'])

# Find the Thursday of the current week
today = pd.Timestamp.today().normalize()
thursday = today + pd.Timedelta((3-today.dayofweek) % 7, unit='D')

# Create a list of expiry dates
expiry_dates = []
for i in range(55):  # assuming there are 55 expiry dates
    expiry_date = thursday + pd.Timedelta(i*7, unit='D')
    expiry_dates.append(expiry_date.strftime('%d%b%y').upper())

# Group the options data by expiry date
groups = df.groupby(df['Date'].dt.strftime('%d%b%y').str.upper())

# Iterate over the groups and print the data for each expiry date
for expiry_date in expiry_dates:
    if expiry_date in groups.groups:
        print(f"Data for expiry date {expiry_date}:")
        print(groups.get_group(expiry_date))
        print()
    else:
        print(f"expiry date {expiry_date}")